services:
  # Flask Web Service
  - type: web
    name: fruit-classifier
    env: python
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
